# codemagic.yaml

workflows:
  main:
    name: Build and Package
    scripts:
      - name: Install Dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Build IPA
        script: |
          expo build:ios -t archive
      
    artifacts:
      - ios/build/**
